version: "3.8"

services:
  portfolio-fe-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-fe-v2
    ports:
      - "3051:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped

volumes:
  node_modules:
